
- name: Get the existing VPC
  ali_vpc_facts:
    region: '{{ item.value.alicloud_region }}'
    vpc_name: '{{ item.value.vpc_name }}'
    alicloud_secret_key: "{{ alicloud_secret_key }}"
    alicloud_access_key: "{{ alicloud_access_key }}"
  register: vpcs
  with_dict: "{{ cloud_bootstrap.vpc_zones }}"

- name: Set Facts VPC_ID_FOR vpc_id
  set_fact: 
    VPC_ID_FOR: "{{ item }}"
  with_items: |
      {% for dict_item in vpcs.results %}{% for k,v in dict_item.items() %}{% if k == 'ids' %}{{ v | join | regex_replace('vpc.+?(?=)(?=\\)', '\\1') }}{% endif %}{% endfor %}{% endfor %}
  register: VPC_ID

- name: Checking the security group
  ali_security_group:
    alicloud_region: '{{ alicloud_region }}'
    name: '{{ sg_name }}'
    group_name: "{{ sg_name }}"
    description: '{{ sg_name }}'
    vpc_id: '{{ VPC_ID_FOR }}'
    rules: '{{ group_inboundRules }}'
    rules_egress: '{{ group_outboundRules }}'
    alicloud_secret_key: "{{ alicloud_secret_key }}"
    alicloud_access_key: "{{ alicloud_access_key }}"
  register: createsgeresult

- name: Quering security group
  ali_security_group:
    alicloud_region: "{{ alicloud_region }}"
    name: '{{ sg_name }}'
    group_id: '{{ createsgeresult.group.group_id }}'
    group_name: "{{ sg_name }}"
    alicloud_secret_key: "{{ alicloud_secret_key }}"
    alicloud_access_key: "{{ alicloud_access_key }}"
    state: present
    vpc_id: "{{ createsgeresult.group.vpc_id }}"
  register: quetysgeresult

- name: Checking the existing vswitch
  ali_vswitch:
    cidr_block: '{{ item.value.vswitch_cidr }}'
    vpc_id: '{{ VPC_ID_FOR }}'
    name: '{{ item.value.vswitch_name }}'
    alicloud_secret_key: "{{ alicloud_secret_key }}"
    alicloud_access_key: "{{ alicloud_access_key }}"
    alicloud_region: "{{ alicloud_region }}"
    alicloud_zone: "{{ alicloud_zone }}"
  register: vswitch
  with_dict: "{{ cloud_bootstrap.switches }}"

- name: Add fact for the vswitch_id
  set_fact: 
    vswitch_id: "{{ item['vswitch']['vswitch_id'] }}"
  with_items: 
    - "{{ vswitch['results'] }}"

- name: Show Alicloud region
  debug:
    msg: "{{ alicloud_region }}"

- name: Stop an ECS instance for maintanance
  ali_instance:
    security_groups: "{{ createsgeresult.group.group_id }}"
    alicloud_region: "{{ alicloud_region }}"
    image: '{{ image_id }}'
    type: '{{ item.value.alicloud_vm_configuration }}'
    instance_name: '{{ item.value.name }}'
    description: '{{ item.value.name }}'
    host_name: '{{ item.value.name }}'
    password: '{{ alicloud_vm_access_pass }}'
    count: '{{ count }}'
    internet_charge_type: "PayByTraffic"
    instance_charge_type: "PostPaid"
    allocate_public_ip: 'true'
    max_bandwidth_in: 10
    max_bandwidth_out: 10
    vswitch_id: '{{ vswitch_id }}'
    alicloud_secret_key: "{{ alicloud_secret_key }}"
    alicloud_access_key: "{{ alicloud_access_key }}"
    state: stopped
  register: stop_instance_result
  with_dict: "{{ cloud_bootstrap.servers }}"

- name: Startback an ECS instance
  ali_instance:
    security_groups: "{{ createsgeresult.group.group_id }}"
    alicloud_region: "{{ alicloud_region }}"
    image: '{{ image_id }}'
    type: '{{ item.value.alicloud_vm_configuration }}'
    instance_name: '{{  item.value.name }}'
    description: '{{  item.value.name }}'
    host_name: '{{  item.value.name }}'
    password: '{{ alicloud_vm_access_pass }}'
    count: '{{ count }}'
    internet_charge_type: "PayByTraffic"
    instance_charge_type: "PostPaid"
    allocate_public_ip: 'true'
    max_bandwidth_in: 10
    max_bandwidth_out: 10
    vswitch_id: '{{ vswitch_id }}'
    alicloud_secret_key: "{{ alicloud_secret_key }}"
    alicloud_access_key: "{{ alicloud_access_key }}"
    state: running
  register: start_instance_result
  with_dict: "{{ cloud_bootstrap.servers }}"