#
# MAIN NGINX SETTINGS
#
############
## ALL SITES
#

### Main Sites
ansible_global_www_site_name: "www.{{ public_consul_domain }}"
ansible_global_prometheus_site_name: "prometheus.{{ public_consul_domain }}"
ansible_global_grafana_site_name: "grafana.{{ public_consul_domain }}"
ansible_global_alertmanager_site_name: "alertmanager.{{ public_consul_domain }}"
ansible_global_consul_site_name: "consul.{{ public_consul_domain }}"
ansible_global_primary_site_name: "{{ public_consul_domain }}"
ansible_global_kibana_site_name: "kibana.{{ public_consul_domain }}"
ansible_global_teamcity_site_name: "teamcity.{{ public_consul_domain }}"
ansible_global_pgmanager_site_name: "pgmanager.{{ public_consul_domain }}"
ansible_global_kubernetes_site_name: "kubernetes.{{ public_consul_domain }}"

### Ossec & Wazuh
ansible_global_wazuh_site_name: "wazuh.{{ public_consul_domain }}"

### Gitlab & Docker registry
ansible_global_gitlab_site_name: "gitlab.{{ public_consul_domain }}"
ansible_global_gitlab_registry_site_name: "registry.{{ public_consul_domain }}"

### NOT NEEDED SITES

nginx_remove_sites: []

### ALL SITES RESULT

nginx_sites: "{{ nginx_result }}"

#################
## NGINX SETTINGS

### Common HTTP Settings
http_server:
  max_request_length: 1191200
  ## in kb
  access_control_allow_origin: "$http_origin"
  cdn_access_control_allow_origin: "*"

#
#######################################
# ANSIBLE DICTIONARY LINKS AND MAPPINGS

###
#{ linked vars for on-fly merge, same for each inventories for nginx-frontend playbook }
###
nginx_configs_locations_kubernetes: "{{ ansible_environment }}_locations_kubernetes"
nginx_configs_upstreams: "{{ ansible_environment }}_upstreams"
nginx_configs_locations: "{{ ansible_environment }}_locations"
nginx_configs_locations_main: "{{ ansible_environment }}_locations_main"
nginx_configs_locations_teamcity: "{{ ansible_environment }}_locations_teamcity"
nginx_configs_locations_pgmanager: "{{ ansible_environment }}_locations_pgmanager"
nginx_configs_locations_core: "{{ ansible_environment }}_locations_core"
nginx_configs_locations_metabase: "{{ ansible_environment }}_locations_metabase"
nginx_configs_locations_prometheus: "{{ ansible_environment }}_locations_prometheus"
nginx_configs_locations_grafana: "{{ ansible_environment }}_locations_grafana"
nginx_configs_locations_alertmanager: "{{ ansible_environment }}_locations_alertmanager"
nginx_configs_locations_wazuh: "{{ ansible_environment }}_locations_wazuh"
nginx_configs_locations_www: "{{ ansible_environment }}_locations_www"
nginx_configs_locations_sentry: "{{ ansible_environment }}_locations_sentry"
nginx_configs_locations_consul: "{{ ansible_environment }}_locations_consul"
nginx_configs_defaults: "{{ ansible_environment }}_defaults"
nginx_configs_locations_acme_well_known: "{{ ansible_environment }}_locations_acme_well_known"
nginx_configs_locations_acme: "{{ ansible_environment }}_locations_acme"
nginx_configs_locations_gitlab: "{{ ansible_environment }}_locations_gitlab"
nginx_configs_locations_registry: "{{ ansible_environment }}_locations_registry"
nginx_configs_locations_kibana: "{{ ansible_environment }}_locations_kibana"

#### Example
# nginx_configs: "{{ nginx_config_defaults |combine(nginx_config_2, nginx_config_3) }}"
# nginx_same: "{{ nginx_config_defaults |combine(nginx_config_locations) }}"
####

### SAME CONFIGS

nginx_config_defaults:
  "{
    '{{ nginx_configs_defaults }}':
         {{ config_defaults | list }}
    }"

nginx_configs:
  "{
    '{{ nginx_configs_upstreams }}':
         {{ unification_upstreams | list }}
    }"

### LOCATIONS OF NGINX FRONTEND

location_kubernetes:
  - location / {
    proxy_pass http://kubernetes_{{ ansible_environment }};
    }

location_pgmanager:
  - location / {
    proxy_pass http://pgmanager_{{ ansible_environment }};
    }

location_wazuh:
  - location / {
    proxy_pass http://wazuh_{{ ansible_environment }};
    auth_basic "Restricted";
    auth_basic_user_file /mnt/cloud-bind-frontend-dns-glusterfs-storage/secured/.htpasswd;
    }

location_consul:
  - location / {
    proxy_pass http://consul_{{ ansible_environment }};
    }

location_www:
  - location / {
    proxy_pass http://www_{{ ansible_environment }};
    }

location_acme_well_known:
  - location ^~ /.well-known/acme-challenge/ {
    alias /core_root/raw_core/opt/nginx-acme/.well-known/acme-challenge/;
    allow all;
    }

location_acme:
  - location / {
    proxy_pass http://acme_{{ ansible_environment }};
    proxy_http_version  1.1;
    proxy_set_header    X-Forwarded-For $remote_addr;
    proxy_set_header    Host $server_name:$server_port;
    }

location_wallet:
  - location / {
    proxy_pass http://wallet_{{ ansible_environment }};
    }

location_teamcity:
  - location / {
    proxy_pass http://teamcity_{{ ansible_environment }};
    }

location_core:
  - location / {
    proxy_pass http://core_{{ ansible_environment }};
    }

location_metabase:
  - location / {
    proxy_pass http://metabase_{{ ansible_environment }};
    }

location_gitlab:
  - location / {
    proxy_pass https://gitlab_{{ ansible_environment }};
    }

location_registry:
  - location / {
    proxy_pass https://registry_{{ ansible_environment }};
    }

location_kibana:
  - location / {
    proxy_pass http://kibana_{{ ansible_environment }};
    auth_basic "Restricted";
    auth_basic_user_file /mnt/cloud-bind-frontend-dns-glusterfs-storage/secured/.htpasswd;
    }
  
location_grafana:
  - location / {
    proxy_pass http://grafana_{{ ansible_environment }};
    }

location_prometheus:
  - location / {
    proxy_pass http://prometheus_{{ ansible_environment }};
    auth_basic "Restricted";
    auth_basic_user_file /mnt/cloud-bind-frontend-dns-glusterfs-storage/secured/.htpasswd;
    }

location_alertmanager:
  - location / {
    proxy_pass http://alertmanager_{{ ansible_environment }};
    auth_basic "Restricted";
    auth_basic_user_file /mnt/cloud-bind-frontend-dns-glusterfs-storage/secured/.htpasswd;
    }

### LOCATIONS CONFIGS

nginx_config_locations_kubernetes:
  "{
    '{{ nginx_configs_locations_kubernetes }}':
         {{ location_kubernetes | list }}
    }"

nginx_config_locations_pgmanager:
  "{
    '{{ nginx_configs_locations_pgmanager }}':
         {{ location_pgmanager | list }}
    }"

nginx_config_locations_www:
  "{
    '{{ nginx_configs_locations_www }}':
         {{ location_www | list }}
    }"

nginx_config_locations_alertmanager:
  "{
    '{{ nginx_configs_locations_alertmanager }}':
         {{ location_alertmanager | list }}
    }"

nginx_config_locations_prometheus:
  "{
    '{{ nginx_configs_locations_prometheus }}':
         {{ location_prometheus | list }}
    }"

nginx_config_locations_grafana:
  "{
    '{{ nginx_configs_locations_grafana }}':
         {{ location_grafana | list }}
    }"

nginx_config_locations_wazuh:
  "{
    '{{ nginx_configs_locations_wazuh }}':
         {{ location_wazuh | list }}
    }"

nginx_config_locations_registry:
  "{
    '{{ nginx_configs_locations_registry }}':
         {{ location_registry | list }}
    }"

nginx_config_locations_gitlab:
  "{
    '{{ nginx_configs_locations_gitlab }}':
         {{ location_gitlab | list }}
    }"

nginx_config_locations_acme_well_known:
  "{
    '{{ nginx_configs_locations_acme_well_known }}':
         {{ location_acme_well_known | list }}
    }"

nginx_config_locations_teamcity:
  "{
    '{{ nginx_configs_locations_teamcity }}':
         {{ location_teamcity | list }}
    }"

nginx_config_locations_core:
  "{
    '{{ nginx_configs_locations_core }}':
         {{ location_core | list }}
    }"

nginx_config_locations_metabase:
  "{
    '{{ nginx_configs_locations_metabase }}':
         {{ location_metabase | list }}
    }"

nginx_config_locations_kibana:
  "{
    '{{ nginx_configs_locations_kibana }}':
         {{ location_kibana | list }}
    }"

### DEFAULT SITES

projects_default_sites:
  - {
    name: "{{ ansible_global_kubernetes_site_name }}",
    published: "enabled",
    value: "wildcard",
    prefix: "{{ ansible_global_kubernetes_site_name }}",
    type: "{{ ansible_global_kubernetes_site_name }}",
    location: "kubernetes",
    config: "defaults"
  }
  - {
    name: "{{ ansible_global_teamcity_site_name }}",
    published: "enabled",
    value: "wildcard",
    prefix: "{{ ansible_global_teamcity_site_name }}",
    type: "{{ ansible_global_teamcity_site_name }}",
    location: "teamcity",
    config: "defaults"
  }
  - {
    name: "{{ ansible_global_kibana_site_name }}",
    published: "enabled",
    value: "wildcard",
    prefix: "{{ ansible_global_kibana_site_name }}",
    type: "{{ ansible_global_kibana_site_name }}",
    location: "kibana",
    config: "defaults"
  }
  - {
    name: "{{ ansible_global_gitlab_registry_site_name }}",
    published: "enabled",
    value: "wildcard",
    prefix: "{{ ansible_global_gitlab_registry_site_name }}",
    type: "{{ ansible_global_gitlab_registry_site_name }}",
    location: "registry",
    config: "defaults"
  }
  - {
    name: "{{ ansible_global_gitlab_site_name }}",
    published: "enabled",
    value: "wildcard",
    prefix: "{{ ansible_global_gitlab_site_name }}",
    type: "{{ ansible_global_gitlab_site_name }}",
    location: "gitlab",
    config: "defaults"
  }
  - {
    name: "{{ ansible_global_primary_site_name }}",
    published: "enabled",
    value: "primary",
    prefix: "{{ ansible_global_primary_site_name }}",
    type: "{{ ansible_global_primary_site_name }}",
    location: "www",
    config: "defaults"
  }
  - {
    name: "{{ ansible_global_grafana_site_name }}",
    published: "enabled",
    value: "wildcard",
    prefix: "{{ ansible_global_grafana_site_name }}",
    type: "{{ ansible_global_grafana_site_name }}",
    location: "grafana",
    config: "defaults"
  }
  - {
    name: "{{ ansible_global_prometheus_site_name }}",
    published: "enabled",
    value: "wildcard",
    prefix: "{{ ansible_global_prometheus_site_name }}",
    type: "{{ ansible_global_prometheus_site_name }}",
    location: "prometheus",
    config: "defaults"
  }
  - {
    name: "{{ ansible_global_alertmanager_site_name }}",
    published: "enabled",
    value: "wildcard",
    prefix: "{{ ansible_global_alertmanager_site_name }}",
    type: "{{ ansible_global_alertmanager_site_name }}",
    location: "alertmanager",
    config: "defaults"
  }
  - {
    name: "{{ ansible_global_wazuh_site_name }}",
    published: "enabled",
    value: "wildcard",
    prefix: "{{ ansible_global_wazuh_site_name }}",
    type: "{{ ansible_global_wazuh_site_name }}",
    location: "wazuh",
    config: "defaults"
  }
  # - {
  #   name: "{{ ansible_global_pgmanager_site_name }}",
  #   published: "enabled",
  #   value: "wildcard",
  #   prefix: "{{ ansible_global_pgmanager_site_name }}",
  #   type: "{{ ansible_global_pgmanager_site_name }}",
  #   location: "pgmanager",
  #   config: "defaults"
  # }
