consul_defaults:
    master_key: "PjqEOgzbgbM00fQxaRQ+IA=="
    directories:
        working_etc_directory: /cloud/local/opt/consul/etc
        working_directory: /cloud/local/opt
        working_opt_directory: /cloud/local/opt/consul/opt
        working_opt_pki: /cloud/local/opt/consul/opt/pki/
        working_opt_pki_cert: /cloud/local/opt/consul/opt/pki/cert        
        working_opt_pki_private: /cloud/local/opt/consul/opt/pki/private
        working_consul: /cloud/local/opt/consul
        working_consul_data: /cloud/local/opt/consul/data
        working_consul_data_raft: /cloud/local/opt/consul/data/raft
        ui_dir: /cloud/local/opt/consul/ui
        configs_dir: /cloud/local/opt/consul/etc/consul.d
        logging_dir: /cloud/local/opt/consul/logs
    datacenter: dc1
    consul_get_url: https://releases.hashicorp.com/consul/1.4.2/consul_1.4.2_linux_amd64.zip
    consul_get_zip: consul_1.4.2_linux_amd64.zip
    consul_security:
        linux_username: consul
        linux_group: consul