unificated_keepalive_services:
  shared_settings:
    notification_email: "admin@ifsholding.com"
    notification_email_from: "keepalived@ifsholding.com"
    smtp_server: "mail.vortex.ru"
    smtp_connect_timeout: 30
    lvs_id: "{{ lvs_id }}"
  vrrp_sync_group:
    - {
      "CPILOT": {
        'external': 
          {
            "auth_pass": "31337PASS1",
            "virtual_ipaddress": "10.0.2.100",
            "interface": "eth0",
            "priority": "{{ hostvars[inventory_hostname].lb_router_priority }}",
            "virtual_router_id": "51",
            "lvs_sync_daemon_inteface": "disabled",
            "smtp_alert": "enabled"
          },
        'internal':
          {
            "auth_pass": "31337PASS1",
            "virtual_ipaddress": "10.30.0.3",
            "interface": "eth1",
            "priority": "{{ hostvars[inventory_hostname].lb_router_priority }}",
            "virtual_router_id": "52",
            "lvs_sync_daemon_inteface": "disabled",
            "smtp_alert": "enabled"
          }
        }
      }
  backend_services:
    - { "teamcity-web": 
        {
        "lb_kind": "NAT",
        "lvs_sched": "rr",
        "protocol": "TCP",
        "vrrp_sync_group": "CPILOT",
        "smtp_alert": "true",
        "delay_loop": {
          "enabled": "true",
          "delay_loop": "6"
        },
        "persistence_timeout": {
          "enabled": "false",
          "persistence_timeout": "900"
        },
        "virtual_server": {
          "ip": "10.0.2.100",
          "check": "TCP_CHECK",
          "port": "9091",
          "weight": "100"
        },
        "backend_server": {
          "group": "teamcity-server",
          "connect_port": "8111",
          "connect_timeout": "5",
          "ip": "default"
        },
        "comment": "http://teamcity.cpilot.ru"
        }
    }