{% raw %}apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
clusterName: "{% endraw %}{{ K8S_CLUSTER_NAME }}{% raw %}"
kubernetesVersion: stable
apiServerCertSANs:
- {% endraw %}{{ K8S_CLUSTER_ADDRESS }}{% raw %}:{% endraw %}{{ K8S_CLUSTER_LISTEN_PORT }}{% raw %}"
controlPlaneEndpoint: "{% endraw %}{{ K8S_CLUSTER_ADDRESS }}{% raw %}:{% endraw %}{{ K8S_CLUSTER_LISTEN_PORT }}{% raw %}"
apiServer:
    timeoutForControlPlane: 4m0s
    advertise-address: 0.0.0.0
    anonymous-auth: "false"
    audit-log-path: /var/log/k8s-api-audit.log
etcd:
  external:
    endpoints:{% endraw %}{% for host in groups['kubernetes-master'] %}{% raw %}
    - https://{% endraw %}{{ hostvars[host]['second_ip'] }}{% raw %}:{% endraw %}{{ K8S_CLUSTER_LISTEN_PORT_2379 }}{% endfor %}{% raw %}
    caFile: /etc/etcd/ca.pem
    certFile: /etc/etcd/kubernetes.pem
    keyFile: /etc/etcd/kubernetes-key.pem
networking:
  podSubnet: {% endraw %}{{ POD_NETWORK_CIDR }}{% raw %}
apiServerExtraArgs:
  apiserver-count: "3"
{% endraw %}