- name: RabbitMQ Swarm Docker Playbook step...
  become: true
  hosts: "{{ HOSTS | default('rabbitmq-cluster') }}"
  roles:
    - name: Setup RabbitMQ Service 
      role: ./!_databases/rabbitmq-docker
  tags: [rabbitmq-setup]

- name: Consul magic JOIN DNS step... Unix work...
  become: true
  hosts: "{{ HOSTS | default('rabbitmq-cluster') }}"
  vars_files:
    - "{{ inventory_dir }}/group_vars/{{ HOSTS }}/{{ HOSTS }}.yml"
  roles:
    - name: Consul magic do...
      role: ./!_cloud/consul/magic-join
  tags: [consul-dns-join]