---
# Dynamic Inventory

# Cpilot docker inventory

ansible_environment: "cpilot-develop"
ansible_product: "cpilot"

default_container_memory: "1G"

### Consul Common

ca_certs_directory: /cloud/local/opt/consul/opt/pki/ca-certs

consul:
    master_key: "PjqEOgzbgbM00fQxaRQ+IA=="
    directories:
        ca_certs_directory: /cloud/local/opt/consul/opt/pki/ca-certs
        working_etc_directory: /cloud/local/opt/consul/etc
        working_directory: /cloud/local/opt
        working_opt_directory: /cloud/local/opt/consul/opt
        working_opt_pki: /cloud/local/opt/consul/opt/pki
        working_opt_pki_cert: /cloud/local/opt/consul/opt/pki/cert        
        working_opt_pki_private: /cloud/local/opt/consul/opt/pki/private
        working_consul: /cloud/local/opt/consul
        working_consul_data: /cloud/local/opt/consul/data
        working_consul_data_raft: /cloud/local/opt/consul/data/raft
        ui_dir: /cloud/local/opt/consul/ui
        configs_dir: /cloud/local/opt/consul/etc/consul.d
        crazy_hop_d: /cloud/local/opt/consul/etc/crazy_hop.d
    consul_name: "cloud-{{ ansible_hostname }}"
    datacenter: "{{ consul_datacenter }}"

#### CONSUL SECTION

consul_teamcity_prefix: "teamcity"
consul_public_prefix: "space"
cosnul_private_prefix: "consul"
consul_powerdns_prefix: "powerdns"
consul_domain_name: "cpilot.consul."
consul_merge_domain_name: "cpilot.space."
consul_datacenter: "dc1"
merge_consul_domain: "cpilot.space"
public_consul_domain: "cpilot.ru"
internal_consul_domain: "cpilot.consul"

### GIT

git_cloud_url: "git.{{ public_consul_domain }}"

#### APPLICATION SITES

cpilot_gateway: "gate.{{ public_consul_domain }}"

#### CLOUD !

ansible_metrics_site_name: "metrics.{{ public_consul_domain }}"
cloud_consul_url: "api.{{ public_consul_domain }}"
consul_cloud_url: "consul.{{ public_consul_domain }}"
teamcity_cloud_url: "teamcity.{{ public_consul_domain }}"
ansible_global_main_site_name: "{{ ansible_environment }}.{{ public_consul_domain }}"
ansible_global_api_site_name: "{{ ansible_environment }}-api.{{ public_consul_domain }}"

## NGINX FRONTEND SITES

### NGINX CORE SETTING
# POSSIBLE VALUES = http_only or https_only

nginx_core_type: http_only

###

unification_sites:
    - { 
        name: "{{ ansible_global_teamcity_site_name }}",
        published: "enabled",
        value: "cert_bot",
        prefix: "{{ ansible_global_teamcity_site_name }}",
        type: "{{ ansible_global_teamcity_site_name }}",
        location: "teamcity",
        config: "defaults" 
      }
    - { 
        name: "{{ teamcity_cloud_url }}",
        published: "enabled",
        value: "cert_bot",
        prefix: "{{ teamcity_cloud_url }}",
        type: "{{ teamcity_cloud_url }}",
        location: "teamcity",
        config: "defaults" 
      }
    - { 
        name: "{{ ansible_global_consul_site_name }}",
        published: "enabled",
        value: "cert_bot", 
        prefix: "{{ ansible_global_consul_site_name }}",
        type: "{{ ansible_global_consul_site_name }}",
        location: "consul",
        config: "defaults" 
      }
    - { 
        name: "{{ cpilot_gateway }}",
        published: "enabled",
        value: "cert_bot", 
        prefix: "{{ cpilot_gateway }}",
        type: "{{ cpilot_gateway }}",
        location: "gate",
        config: "defaults" 
      }
    - { 
        name: "gateway.cpilot.ru",
        published: "disabled",
        value: "cert_bot", 
        prefix: "{{ cpilot_gateway }}",
        type: "{{ cpilot_gateway }}",
        location: "gate",
        config: "defaults" 
      }
    - { 
        name: "{{ git_cloud_url }}",
        published: "enabled",
        value: "cert_bot", 
        prefix: "{{ git_cloud_url }}", 
        type: "{{ git_cloud_url }}", 
        location: "git_website", 
        config: "defaults"
      }

unification_services:
    - {'teamcity': {'target': 'teamcity-server', 'listen_port': "{{ teamcity_service_listen_port }}", 'check_type': "script", 'script_check': "{% for host in groups['teamcity-server'] %}curl http://{{ hostvars[host].ansible_default_ipv4.address }}:{{ teamcity_service_listen_port }} && echo 'success' || echo 'fail'{% endfor %}" }}
    - {'consul': {'target': 'consul-masters', 'listen_port': "{{ consul_service_listen_port }}", 'check_type': "script", 'script_check': "curl http://{{ inventory_hostname }}:{{ consul_service_listen_port }} && echo 'success' || echo 'fail'" }}
    - {'gate': {'target': 'gate-cluster', 'listen_port': "{{ gate_service_listen_port }}", 'check_type': "script", 'script_check': "curl http://{{ inventory_hostname }}:{{ gate_service_listen_port }} && echo 'success' || echo 'fail'" }}
    - {'git_website': {'target': 'gitlab-server', 'listen_port': "{{ git_service_listen_port }}" }}

unification_services_for_check:
    - {'powerdns-raw53': {'target': 'consul-masters', 'listen_port': "{{ dns_service_listen_port }}", 'check_type': "script", 'script_check': "netstat -apnu | grep 53 && echo 'success' || echo 'fail'" }}
    - {'ns': {'target': 'consul-masters', 'listen_port': "{{ dns_service_listen_port }}", 'check_type': "script", 'script_check': "dig @{{ ansible_default_ipv4['address'] }} {{ consul_domain_name }}&& echo 'success' || echo 'fail'" }}

crazy_hop_consul_services:
    - {'cloud-ns': { 'name': 'cloud-ns', 'exec': 'py', 'type': 'external_body', 'script': "nill" }}
    - {'services': { 'name': 'services', 'exec': 'py', 'type': 'external_body', 'script': "nill" }}

unificated_consul_services: "{{ unification_services }}"

basic_consul_services:
    - {'ram': {'target': 'all', 'check_type': "script", 'script_check': "intel_inside_already_we_have" }} 
    - {'cpu': {'target': 'all', 'check_type': "script", 'script_check': "intel_inside_already_we_have" }} 
    - {'disks': {'target': 'all', 'check_type': "script", 'script_check': "intel_inside_already_we_have" }} 

####

primary_vbox_api: "{{ inventory_hostname }}"

## Main Sites
ansible_global_consul_site_name: "consul.{{ public_consul_domain }}"
ansible_global_teamcity_site_name: "teamcity.{{ public_consul_domain }}"

### Common HTTP Settings
http_server:
    max_request_length: 91200
    ## in kb
    access_control_allow_origin: "$http_origin"
    cdn_access_control_allow_origin: "*"

# HTTP Only
nginx_result: "{{ unificated_sites_without_https + host_default_name_site }}"

# HTTP + > HTTPS configuration
# nginx_result: "{{ unificated_sites_https + unificated_sites_http + host_default_name_site }}"

nginx_same: "{{ nginx_config_defaults |combine(nginx_config_locations_gate,nginx_config_locations_consul,nginx_config_locations_teamcity,nginx_config_locations_git_website) }}"

ansible_port: 22

#### PORTS FOR INVENTORY

### GIT

git_service_listen_port: 8094
git_inside_container_listen_port: 80

### Api Service Port
gate_service_listen_port: 5674

### HTTP
http_service_listen_port: 80
https_service_listen_port: 443

### < MAIN POSTGRES CLUSTER FEATURE
postgres_main_cluster_listen_port: 7852

### PostgreSQL Service Port
postgresql_service_listen_port: 5432

### TeamCity Listen Port
vnc_service_listen_port: 5999
teamcity_service_listen_port: 8111

### Consul
consul_service_listen_port: 8500

### SAME CONFIGS

nginx_config_defaults:
          "{
    '{{ nginx_configs_defaults }}':
         {{ config_defaults | list }}
    }"

nginx_configs:
          "{
    '{{ nginx_configs_upstreams }}':
         {{ unification_upstreams | list }}
    }"
    
### LOCATIONS CONFIGS

nginx_config_locations_acme_well_known:
          "{
    '{{ nginx_configs_locations_acme_well_known }}':
         {{ location_acme_well_known | list }}
    }"

nginx_config_locations_consul:
          "{
    '{{ nginx_configs_locations_consul }}': 
         {{ location_consul | list }}
    }"

nginx_config_locations_teamcity:
          "{
    '{{ nginx_configs_locations_teamcity }}':
         {{ location_teamcity | list }}
    }"

nginx_config_locations_gate:
          "{
    '{{ nginx_configs_locations_gate }}':
         {{ location_gate | list }}
    }"

nginx_config_locations_git_website:
          "{
    '{{ nginx_configs_locations_git_website }}':
         {{ location_git_website | list }}
    }"


##### LOCATIONS OF NGINX FRONTEND

location_git_website:
    - location / {
        proxy_pass http://git_website_{{ ansible_environment }};
        proxy_http_version  1.1;
        proxy_set_header    X-Forwarded-For $remote_addr;
        proxy_set_header    Host $server_name:$server_port;
      }

location_teamcity:
    - location / {
          proxy_pass http://teamcity_{{ ansible_environment }};
      }

location_consul:
    - location / {
          proxy_pass http://consul_{{ ansible_environment }};
      }

location_gate:
    - location / {
          proxy_pass http://gate_{{ ansible_environment }};
      }