
- name: Bootstrap infrastructure from localhost to ESXi Vcenter Appliance
  hosts: localhost
  gather_facts: False
  tasks:
    
    - name: Debug dict
      debug:
        msg: "{{ item.value.network }} {{ item.value.ip }} {{ item.value.name }}"
      with_dict: "{{ vsphere_bootstrap.servers }}"
    
    - name: ONE NET | Test debug when second_ip == null
      debug:
        msg: "{{ item.value.ip }} {{ lookup('random_mac') }}"
      when: (item.value.second_ip is defined and item.value.second_ip == '') or (item.value.second_ip is not defined) or (item.value.second_ip == 'null')
      with_dict: "{{ vsphere_bootstrap.servers }}"
    
    - name: MULTI NET | Test debug when second_ip != null
      debug:
        msg: "{{ item.value.ip }} {{ lookup('random_mac') }}"
      when: item.value.second_ip is defined and item.value.second_ip != '' and item.value.second_ip != 'null'
      with_dict: "{{ vsphere_bootstrap.servers }}"

    - name: STOPPING | Stopping a VM and prepare customize
      vmware_guest:
        hostname: "{{ vsphere_fqdn }}"
        username: "{{ vsphere_login }}"
        password: "{{ vsphere_pass }}"
        validate_certs: no
        datacenter: "{{ vsphere_dc }}"
        folder: "/"
        name: "{{ item.value.name }}"
        state: poweredoff
      with_dict: "{{ vsphere_bootstrap.servers }}"

    - name: ONE NET | Clone a VM from Template and customize, when one network
      vmware_guest:
        hostname: "{{ vsphere_fqdn }}"
        username: "{{ vsphere_login }}"
        password: "{{ vsphere_pass }}"
        validate_certs: no
        datacenter: "{{ vsphere_dc }}"
        folder: "/"
        name: "{{ item.value.name }}"
        template: "{{ vsphere_template_name }}"
        networks:
        - name: "{{ item.value.network }}"
          ip: "{{ item.value.ip }}"
          netmask: 255.255.255.0
          gateway: "{{ item.value.gw }}"
          mac: "{{ lookup('random_mac') }}"
          domain: "{{ vsphere_domain }}"
          dns_servers: "{{ dns_servers }}"
          start_connected: True
        hardware:
          memory_mb: "{{ item.value.memory_size_mb | default('1024') }}"
          num_cpus: "{{ item.value.cpu_count  | default('2') }}"
        resource_pool: "{{ item.value.resource_pool | default('non_prod') }}"
        state: poweredon
      when: (item.value.second_ip is defined and item.value.second_ip == '') or (item.value.second_ip is not defined) or (item.value.second_ip == 'null')
      with_dict: "{{ vsphere_bootstrap.servers }}"

    - name: MULTI NET | Clone a VM from Template and customize, when more then one network
      vmware_guest:
        hostname: "{{ vsphere_fqdn }}"
        username: "{{ vsphere_login }}"
        password: "{{ vsphere_pass }}"
        validate_certs: no
        datacenter: "{{ vsphere_dc }}"
        folder: "/"
        name: "{{ item.value.name }}"
        template: "{{ vsphere_template_name }}"
        networks:
        - name: "{{ item.value.network }}"
          ip: "{{ item.value.ip }}"
          netmask: 255.255.255.0
          gateway: "{{ item.value.gw }}"
          mac: "{{ lookup('random_mac') }}"
          domain: "{{ vsphere_domain }}"
          dns_servers: "{{ dns_servers }}"
        - name: "{{ item.value.second_network }}"
          ip: "{{ item.value.second_ip }}"
          netmask: 255.255.255.0
          mac: "{{ lookup('random_mac') }}"
        hardware:
          memory_mb: "{{ item.value.memory_size_mb | default('1024') }}"
          num_cpus: "{{ item.value.cpu_count  | default('2') }}"
        resource_pool: "{{ item.value.resource_pool | default('non_prod') }}"
        state: poweredon
      when: item.value.second_ip is defined and item.value.second_ip != '' and item.value.second_ip != 'null'
      with_dict: "{{ vsphere_bootstrap.servers }}"