- name: Run the pansearch role on all servers in group pansearch-hosts
  become: true
  hosts: "{{ HOSTS | default('pansearch-hosts') }}"
  roles:
    - name: Run the pansearch role
      role: ./!_security/scripts/pansearch
  tags: 
    - pansearch