- name: Create the directories for configuration
  file:
    path: "{{ item.value }}"
    state: directory
    mode: 0750
  with_dict: "{{ etcd_service_settings.directories | default({}) }}"
  tags: [configuration,etcd]

- name: Create systemd config from template
  template: 
      src: etcd-systemd.service
      dest: "/etc/systemd/system/etcd.service"

- name: Download Etcd Unix
  get_url:
    url: "{{ etcd_service_settings.etcd_get_url }}"
    dest: "{{ etcd_service_settings.directories.data }}"
  when: download_etcd is defined 

- name: Copy Etcd Binary to /bin
  unarchive:
     src: "{{ etcd_service_settings.directories.data }}/{{ etcd_service_settings.etcd_get_zip }}"
     dest: "{{ etcd_service_settings.directories.source }}"
     copy: no
  when: download_etcd is defined 

- name: Local copy from source
  shell: "cp {{ etcd_service_settings.directories.source }}/{{ etcd_service_settings.etcd_arc_ver }}/etcd* /usr/local/bin/"
  ignore_errors: true
  when: download_etcd is defined 

# - name: Copy all certificates from ca to etcd main config directory
#   shell: "cp -R {{ etcd_service_settings.directories.ca }}/* {{ etcd_service_settings.directories.etc }}"

# - name: Register contents of etcd main config directory
#   command: "ls -la {{ etcd_service_settings.directories.etc }}"
#   register: etcd_service_settings_directories_etc
  # when: debug_playbook is defined

# - name: Show contents of etcd main config directory
#   debug:
#     msg: "{{ etcd_service_settings_directories_etc.stdout_lines }}"
  # when: debug_playbook is defined

- name: System Reread Configs for systemd
  systemd:
    daemon_reload: yes

- name: Enable Etcd service and ensure it is not masked
  systemd:
    name: etcd
    enabled: yes
    masked: no

- name: Reload etcd service
  systemd:
    state: restarted
    daemon_reload: yes
    name: etcd

- name: Get status from etcd
  command: etcdctl member list
  register: etcdctl_status_member_list
  # when: debug_playbook is defined

- name: Show status from etcd
  debug:
    msg: "{{ etcdctl_status_member_list.stdout_lines }}"
  # when: debug_playbook is defined