---
# General RabbitMQ parameters that apply to this role itself
rabbitmq_version: latest
rabbitmq_server_state: present
rabbitmq_server_purge: no
rabbitmq_ulimit: 65536

# RabbitMQ config parameters
rabbitmq_amqp_port: 5672
rabbitmq_epmd_port: 4369
rabbitmq_node_port: 25672
rabbitmq_memory_high_watermark: 0.5
rabbitmq_disk_free_limit: 1GB
rabbitmq_queue_master_locator: min-masters
rabbitmq_hipe_compile: "false"

# RabbitMQ plugins
rabbitmq_plugins:
  - name: rabbitmq_management
    state: enabled
  - name: rabbitmq_management_agent
    state: enabled

# RabbitMQ management of vhosts, users,...
rabbitmq_remove_guest: false
rabbitmq_vhosts: []
rabbitmq_users: []
rabbitmq_queues: []
rabbitmq_exchanges: []

# RabbitMQ cluster parameters
rabbitmq_cluster: false
rabbitmq_cluster_master: false
rabbitmq_master: vortex-rabbit-01
rabbitmq_erlang_cookie: NEPTQRGCQDKAHSOSFDML


unification_services:
    - {'rabbitmq': {'target': 'rabbitmq-cluster', 'listen_port': "{{ rabbitmq_service_listen_port }}", 'check_type': "tcp", 'script_check': "{{ inventory_hostname }}:{{ rabbitmq_service_listen_port }}" }}

rabbitmq_vhosts_and_settings:
  - { name: "financial_reports", password: "walsh-pica-append-name-bosom-david-papal-buoy" }
  - { name: "gateway_mcom", password: "burly-glad-dell-raoul-lasso-whose-wry-sax" }
  - { name: "merchant", password: "lymph-alway-weary-dandy" }
  - { name: "merchant_reports", password: "dd-elsie-tuna-rajah-equip-size-scrape-juju-mirage-luxe" }
  - { name: "paymarket", value: "d-dell-raod-elsie-tuna-rajah-equip-sizul-lasso-wh" }
  - { name: "topups-tele2", password: "pTpCOvVziGr6We8SJ0gq" }
  - { name: "dolgonosic", password: "asd819hr1br12br18qQ" }
  - { name: "yuldashev", password: "asd819hr1br12br18qQ" }
  - { name: "vortex", password: "asd819hr1br12br18qQ" }